services:
  web-core:
    build: ./web-core
    container_name: web-core
    ports:
      - "3000:3000"
    depends_on:   
      postgres:
          condition: service_healthy   
      mosquitto:
          condition: service_started
    networks:
      - core-network

  ai-core:
    build: ./ai-core
    container_name: ai-core
    depends_on:   
      mosquitto:
          condition: service_started
    networks:
      - core-network
    environment:
      - HOST=mosquitto
      - PORT=1884
      - CLIENT_NAME=ai-client
      - PUBLISHER_NAME=ai-publisher
      - KEEP_ALIVE=60
      - REQ_TOPIC=/ai
      - RES_TOPIC=/tts
      - GOOGLE_API_KEY=AIzaSyCClkGtSBswzvxnPcIR6d6C-ldjfTI_i6s

  schedule-core:
    build: ./schedule-core
    container_name: schedule-core
    ports:
      - "5000:5000"
    depends_on:   
      postgres:
          condition: service_healthy   
      mosquitto:
          condition: service_started
    networks:
      - core-network
    environment:
      - HOST=mosquitto
      - PORT=1884
      - CLIENT_NAME=schedule-core
      - PUBLISHER_NAME=schedule-publisher
      - KEEP_ALIVE=60
      - REQ_TOPIC=/schedule
      - RES_TOPIC=/luna
      - BD_USER=postgres
      - BD_PASSWORD=postgres
      - BD_HOST=postgres
      - BD_PORT=5432
      - BD_NAME=luna
      - FLASK_APP=server.py
      - TOKEN=token

  history-core:
    build: ./history-core
    container_name: history-core
    depends_on:   
      postgres:
          condition: service_healthy   
      mosquitto:
          condition: service_started
    networks:
      - core-network
    environment:
      - HOST=mosquitto
      - PORT=1884
      - CLIENT_NAME=history-client
      - PUBLISHER_NAME=history-publisher
      - KEEP_ALIVE=60
      - REQ_TOPIC=/history
      - RES_TOPIC=/history/message
      - BD_USER=postgres
      - BD_PASSWORD=postgres
      - BD_HOST=postgres
      - BD_PORT=5432
      - BD_NAME=luna

  pghero:
    image: ankane/pghero
    container_name: pghero
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/luna
    networks:
      - core-network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1884:1884"
      - "8884:8884"
    networks:
      - core-network
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "test"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    environment:
      PGUSER: postgres
      POSTGRES_DB: luna
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - core-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  core-network:
    driver: bridge
