name: Build and Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and test Docker Compose
      run: |
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml up -d
        docker compose -f docker-compose.yml ps
        docker compose -f docker-compose.yml down
